ebook_metadata:
  title: ༄༅། །ཆོས་མངོན་པ་མཛོད་ཀྱི་སྤང་བྱ་སྤོང་ཚུལ་གྱི་དཀའ་འགྲེལ་ལེགས་བཤད་ཉི་མའི་འོད་ཟེར་ལས་མཁས་པའི་གཏམ་བྱ་གསང་བ་སྒོ་འབྱེད་ཅེས་བྱ་བ་བཞུགས་སོ།
    །
  authors:
  - མཛད་པ་པོ། མང་ཐོས་ཀླུ་སྒྲུབ་རྒྱ་མཚོ།
  sku: IBA-LG-03-1
  layers:
  - book_title
  - author
  - quotation
web_metadata:
  title:
    en: Advice of the Learned to Unlock the Secret:An Explanation on the Difficult
      Points of Abandoning the Discards in Abhidharma Text “Instruction of Sunlight”
    bo: ཆོས་མངོན་པ་མཛོད་ཀྱི་སྤང་བྱ་སྤོང་ཚུལ་གྱི་དཀའ་འགྲེལ་ལེགས་བཤད་ཉི་མའི་འོད་ཟེར་ལས་མཁས་པའི་གཏམ་བྱ་གསང་བ་སྒོ་འབྱེད།
  collection:
    en: IBA Ludrup Gyatso Series–  Book 3
    bo: ཀླུ་སྒྲུབ་རྒྱ་མཚོ་རྩོམ་བྲིས།–  དེབ། ༣
  author:
    en: Mangtho Ludrup Gyatso
    bo: མང་ཐོས་ཀླུ་སྒྲུབ་རྒྱ་མཚོ།
  pusblisher:
    en: IBA Publications
    bo: རྒྱལ་ཡོངས་གསུང་རབ་སློབ་གཉེར་ཁང་།
  sku: IBA-LG-03-1
  category:
    en: Abhidharma
    bo: ཆོས་མངོན་པ།
  org:
    bo: Timeless Treasuries
    en: མཐའ་ཡས་དཔེ་མཛོད།
  website: http://dharmacloud.tsadra.org
  aquisition_data: '2019-07-18'
  filename: IBA-LG-03-1.epub
  description:
    en: This text is considered to be very important because it clearly outline the
      practice of overcoming the varieties of afflictions through the method of meditation.
    bo: འདིར་ཆོས་མངོན་པ་ལས་ཕྲ་རྒྱས་སོགས་དང་སྦྱར་ནས་ཉམས་ལེན་སྐབས་ཟག་བཅས་དེའི་གཉེན་པོ་བརྟེན་ཚུལ་ལེགས་པར་བསྟན་ཡོད།
